/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmyapp;

public class App {



  public static void main(String[] args) {
    MemberHandler.inputMembers();

    System.out.println();

    MemberHandler.printMembers();
  }



}
